// THIS FILE IS AUTOMATICALLY GENERATED BY `cargo xtask codegen`. DO NOT EDIT MANUALLY.
import { invoke } from '@tauri-apps/api/core';

export async function invoke_windowMinimize(window: any): Promise<void> {
  return invoke('window_minimize', { window: window });
}

export async function invoke_windowMaximize(window: any): Promise<void> {
  return invoke('window_maximize', { window: window });
}

export async function invoke_windowClose(window: any): Promise<void> {
  return invoke('window_close', { window: window });
}

export async function invoke_windowStartDragging(window: any): Promise<void> {
  return invoke('window_start_dragging', { window: window });
}

export async function invoke_isVaultInitialized(): Promise<boolean> {
  return invoke('is_vault_initialized');
}

export async function invoke_validateVaultPassword(password: string): Promise<boolean> {
  return invoke('validate_vault_password', { password: password });
}

export async function invoke_lockVault(): Promise<any> {
  return invoke('lock_vault');
}

export async function invoke_changeMasterPassword(oldPassword: string, newPassword: string): Promise<any> {
  return invoke('change_master_password', { old_password: oldPassword, new_password: newPassword });
}

export async function invoke_resetVault(): Promise<any> {
  return invoke('reset_vault');
}

export async function invoke_listProfiles(): Promise<any[]> {
  return invoke('list_profiles');
}

export async function invoke_saveProfile(input: any, callerProfileId: string): Promise<any> {
  return invoke('save_profile', { input: input, caller_profile_id: callerProfileId });
}

export async function invoke_verifyPin(profileId: string, pin: string): Promise<boolean> {
  return invoke('verify_pin', { profile_id: profileId, pin: pin });
}

export async function invoke_listNotes(callerProfileId: string, isOwner: boolean): Promise<any[]> {
  return invoke('list_notes', { caller_profile_id: callerProfileId, is_owner: isOwner });
}

export async function invoke_saveNote(input: any, callerProfileId: string): Promise<any> {
  return invoke('save_note', { input: input, caller_profile_id: callerProfileId });
}

export async function invoke_deleteNote(id: string, callerProfileId: string): Promise<any> {
  return invoke('delete_note', { id: id, caller_profile_id: callerProfileId });
}

export async function invoke_getAiSettings(): Promise<any> {
  return invoke('get_ai_settings');
}

export async function invoke_saveAiSettings(settings: any): Promise<any> {
  return invoke('save_ai_settings', { settings: settings });
}

export async function invoke_setAiApiKey(apiKey: string): Promise<any> {
  return invoke('set_ai_api_key', { api_key: apiKey });
}

export async function invoke_clearAiApiKey(): Promise<any> {
  return invoke('clear_ai_api_key');
}

export async function invoke_aiPreviewContext(level: any): Promise<any> {
  return invoke('ai_preview_context', { level: level });
}

export async function invoke_aiChat(prompt: string, privacyLevel: any | null, consentGiven: boolean | null): Promise<any> {
  return invoke('ai_chat', { prompt: prompt, privacy_level: privacyLevel, consent_given: consentGiven });
}

export async function invoke_submitFeedback(rating: number, content: string, name: string | null, profession: string | null): Promise<any> {
  return invoke('submit_feedback', { rating: rating, content: content, name: name, profession: profession });
}

export async function invoke_getPendingCrashReport(): Promise<any | null> {
  return invoke('get_pending_crash_report');
}

export async function invoke_dismissCrashReport(id: string, neverAgain: boolean | null): Promise<any> {
  return invoke('dismiss_crash_report', { id: id, never_again: neverAgain });
}

export async function invoke_exportEncryptedBackup(password: string): Promise<number[]> {
  return invoke('export_encrypted_backup', { password: password });
}

export async function invoke_importEncryptedBackup(data: number[], password: string): Promise<any> {
  return invoke('import_encrypted_backup', { data: data, password: password });
}

export async function invoke_getPerformancePrefs(): Promise<any> {
  return invoke('get_performance_prefs');
}

export async function invoke_setPerformancePrefs(prefs: any): Promise<any> {
  return invoke('set_performance_prefs', { prefs: prefs });
}

