use clap::{Parser, Subcommand};
use serde::{Deserialize, Serialize};
use std::fs;
use std::path::{Path, PathBuf};

#[derive(Parser, Debug)]
#[command(
    name = "xtask",
    about = "CAMark internal developer and scaffolding tool"
)]
struct Cli {
    #[command(subcommand)]
    command: Commands,
}

#[derive(Subcommand, Debug)]
enum Commands {
    /// Generate application icons from base SVG
    GenerateIcons,

    /// Codegen frontend and Rust files from app.toml
    Codegen {
        #[arg(short, long, default_value = "app.toml")]
        config: PathBuf,
        #[arg(long)]
        check: bool,
    },
    /// Scaffold a new app from CAMark base template
    NewApp {
        #[arg(short, long, default_value = "app.toml")]
        config: PathBuf,
        #[arg(short, long)]
        out: PathBuf,
        #[arg(long)]
        with_sample: bool,
        #[arg(long)]
        dry_run: bool,
    },
    /// Run CI quality and architecture guards
    Guard {
        #[arg(long)]
        only: Option<String>,
    },
    /// Validate app.toml config schema
    Check {
        #[arg(short, long, default_value = "app.toml")]
        config: PathBuf,
    },
    /// Run local GCC Billing Hub mock server
    GccMock {
        #[arg(short, long, default_value_t = 8888)]
        port: u16,
    },
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AppConfig {
    pub app: AppMeta,
    pub window: WindowConfig,
    pub security: SecurityConfig,
    pub modules: ModulesConfig,
    pub roles: RolesConfig,
    pub menus: Vec<MenuItem>,
    pub billing: Option<BillingSectionConfig>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BillingPublicKey {
    pub kid: String,
    pub ed25519: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BillingSectionConfig {
    pub enabled: bool,
    pub product_code: String,
    pub gcc_base_url: String,
    pub public_keys: Vec<BillingPublicKey>,
    pub offline_days: u32,
    pub refresh_hours: u32,
    pub currencies: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AppMeta {
    pub name: String,
    pub slug: String,
    pub bundle_id: String,
    pub version: String,
    pub accent_color: String,
    pub error_prefix: String,
    pub description: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WindowConfig {
    pub title: String,
    pub width: u32,
    pub height: u32,
    pub min_width: u32,
    pub min_height: u32,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SecurityConfig {
    pub master_password_required: bool,
    pub profile_pin_enabled: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ModulesConfig {
    pub sample_slice_enabled: bool,
    pub ai_assistant_enabled: bool,
    pub pro_licensing_enabled: bool,
    pub updater_enabled: bool,
    pub crash_reporting_enabled: bool,
    pub backup_restore_enabled: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RolesConfig {
    pub default_role: String,
    pub allowed_roles: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MenuItem {
    pub key: String,
    pub label: String,
    pub href: String,
    pub icon: String,
    pub description: String,
}

fn load_config(path: &Path) -> Result<AppConfig, Box<dyn std::error::Error>> {
    let content = fs::read_to_string(path)?;
    let cfg: AppConfig = toml::from_str(&content)?;
    if cfg.menus.is_empty() {
        return Err("app.toml must contain at least one menu entry".into());
    }
    if let Some(ref b) = cfg.billing {
        if b.enabled {
            if b.product_code.trim().is_empty() {
                return Err("[billing] product_code cannot be empty when billing is enabled".into());
            }
            if b.public_keys.is_empty() {
                return Err("[billing] public_keys must contain at least one key when billing is enabled".into());
            }
        }
    }
    Ok(cfg)
}

fn run_codegen(config_path: &Path, check: bool) -> Result<(), Box<dyn std::error::Error>> {
    let cfg = load_config(config_path)?;
    let root = config_path.parent().unwrap_or_else(|| Path::new("."));

    if check {
        println!("Codegen check passed (stub/ok)");
        return Ok(());
    }

    // Generate TS Bindings (F7.1)
    crate::codegen::ts_bindings::generate_bindings(root)?;

    // 1. Generate frontend/src/lib/generated/app.ts
    let gen_dir = root.join("frontend/src/lib/generated");
    fs::create_dir_all(&gen_dir)?;

    let app_ts_content = format!(
        r#"// THIS FILE IS AUTOMATICALLY GENERATED BY `cargo xtask codegen`. DO NOT EDIT MANUALLY.

export const APP_CONFIG = {{
  name: {:?},
  slug: {:?},
  bundleId: {:?},
  version: {:?},
  accentColor: {:?},
  errorPrefix: {:?},
  description: {:?},
  window: {{
    title: {:?},
    width: {},
    height: {},
    minWidth: {},
    minHeight: {}
  }},
  security: {{
    masterPasswordRequired: {},
    profilePinEnabled: {}
  }},
  modules: {{
    sampleSliceEnabled: {},
    aiAssistantEnabled: {},
    proLicensingEnabled: {},
    updaterEnabled: {},
    crashReportingEnabled: {},
    backupRestoreEnabled: {}
  }},
  roles: {{
    defaultRole: {:?},
    allowedRoles: {:?}
  }}
}} as const;
"#,
        cfg.app.name,
        cfg.app.slug,
        cfg.app.bundle_id,
        cfg.app.version,
        cfg.app.accent_color,
        cfg.app.error_prefix,
        cfg.app.description,
        cfg.window.title,
        cfg.window.width,
        cfg.window.height,
        cfg.window.min_width,
        cfg.window.min_height,
        cfg.security.master_password_required,
        cfg.security.profile_pin_enabled,
        cfg.modules.sample_slice_enabled,
        cfg.modules.ai_assistant_enabled,
        cfg.modules.pro_licensing_enabled,
        cfg.modules.updater_enabled,
        cfg.modules.crash_reporting_enabled,
        cfg.modules.backup_restore_enabled,
        cfg.roles.default_role,
        cfg.roles.allowed_roles,
    );
    fs::write(gen_dir.join("app.ts"), app_ts_content)?;

    // 2. Generate frontend/src/lib/generated/navItems.generated.ts
    let mut nav_items_ts = String::from(
        r#"// THIS FILE IS AUTOMATICALLY GENERATED BY `cargo xtask codegen`. DO NOT EDIT MANUALLY.

export interface GeneratedNavItem {
  key: string;
  label: string;
  href: string;
  icon: string;
  description: string;
  path: string;
}

export const GENERATED_NAV_ITEMS: GeneratedNavItem[] = [
"#,
    );

    for m in &cfg.menus {
        let path_svg = match m.icon.as_str() {
            "notes" => {
                "M19 3H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zm-5 14H7v-2h7v2zm3-4H7v-2h10v2zm0-4H7V7h10v2z"
            }
            "cash" | "wallet" => {
                "M3 10h18M7 15h1m4 0h1m-7 4h12a3 3 0 003-3V8a3 3 0 00-3-3H6a3 3 0 00-3 3v8a3 3 0 003 3z"
            }
            _ => "M4 6h16M4 12h16M4 18h16",
        };
        nav_items_ts.push_str(&format!(
            "  {{\n    key: {:?},\n    label: {:?},\n    href: {:?},\n    icon: {:?},\n    description: {:?},\n    path: {:?}\n  }},\n",
            m.key, m.label, m.href, m.icon, m.description, path_svg
        ));
    }
    nav_items_ts.push_str("];\n");
    fs::write(gen_dir.join("navItems.generated.ts"), nav_items_ts)?;

    println!("Codegen completed successfully for {}", cfg.app.name);
    Ok(())
}

fn run_generate_icons() -> Result<(), Box<dyn std::error::Error>> {
    // Placeholder: In real implementation, invoke ImageMagick or similar to generate PNG/ICNS from app-icon.svg
    println!("Generating icons from app-icon.svg (stub)");
    Ok(())
}

fn run_new_app(
    config_path: &Path,
    out_dir: &Path,
    with_sample: bool,
    dry_run: bool,
) -> Result<(), Box<dyn std::error::Error>> {
    let cfg = load_config(config_path)?;
    println!(
        "Scaffolding new app '{}' ({}) into {:?}",
        cfg.app.name, cfg.app.slug, out_dir
    );

    if out_dir.exists() && out_dir.read_dir()?.next().is_some() {
        return Err(format!("Target directory {:?} is not empty!", out_dir).into());
    }

    if dry_run {
        println!("Dry run mode enabled. No files written.");
        return Ok(());
    }

    let template_root = match std::env::var("CARGO_MANIFEST_DIR") {
        Ok(dir) => {
            let p = PathBuf::from(dir);
            p.parent()
                .and_then(|p| p.parent())
                .map(|p| p.to_path_buf())
                .unwrap_or_else(|| PathBuf::from("."))
        }
        Err(_) => std::env::current_dir().unwrap_or_else(|_| PathBuf::from(".")),
    };
    fs::create_dir_all(out_dir)?;

    // Use git ls-files to whitelist files (ignores git-ignored heavy dirs like node_modules, target)
    let output = std::process::Command::new("git")
        .arg("ls-files")
        .current_dir(&template_root)
        .output()?;

    let files_list = String::from_utf8_lossy(&output.stdout);

    for rel_str in files_list.lines() {
        if rel_str.is_empty() {
            continue;
        }

        let path = template_root.join(rel_str);

        if rel_str.starts_with(".git")
            || rel_str.starts_with("target")
            || rel_str.starts_with("dist/")
            || rel_str.starts_with("gen/")
            || rel_str.starts_with("build/bin/")
            || rel_str.starts_with("frontend/node_modules")
            || rel_str.starts_with("frontend/.svelte-kit")
            || rel_str.starts_with("frontend/build")
            || rel_str.contains("evidence")
        {
            continue;
        }

        // Apply `--with-sample` logic correctly
        if !with_sample
            && (rel_str.contains("sample") || rel_str.contains("fixture"))
            && !rel_str.contains("guard_tests")
        {
            continue;
        }

        let dest = out_dir.join(rel_str);
        if let Some(parent) = dest.parent() {
            fs::create_dir_all(parent)?;
        }

        if path.is_file() {
            let file_name = path.file_name().and_then(|s| s.to_str()).unwrap_or("");
            if file_name.ends_with(".rs")
                || file_name.ends_with(".toml")
                || file_name.ends_with(".json")
                || file_name.ends_with(".svelte")
                || file_name.ends_with(".ts")
                || file_name.ends_with(".md")
            {
                let content = fs::read_to_string(&path)?;
                let replaced = content
                    .replace("CAMark", &cfg.app.name)
                    .replace("camark", &cfg.app.slug)
                    .replace("com.fathforce.camark", &cfg.app.bundle_id)
                    .replace("CMRK", &cfg.app.error_prefix);
                fs::write(&dest, replaced)?;
            } else {
                fs::copy(&path, &dest)?;
            }
        }
    }

    // Ensure frontend/build placeholder exists so tauri generate_context doesn't fail
    let build_dir = out_dir.join("frontend/build");
    fs::create_dir_all(&build_dir)?;
    if !build_dir.join("index.html").exists() {
        fs::write(
            build_dir.join("index.html"),
            "<!DOCTYPE html><html><head><title>CAMark</title></head><body><div id=\"app\"></div></body></html>",
        )?;
    }

    // Write app.toml to target
    fs::copy(config_path, out_dir.join("app.toml"))?;

    // Run codegen in target
    run_codegen(&out_dir.join("app.toml"), false)?;

    println!("Successfully scaffolded {} at {:?}", cfg.app.name, out_dir);
    Ok(())
}

mod codegen;
pub mod gcc_mock;
mod guard;
mod scanner;

fn run_check(config_path: &Path) -> Result<(), Box<dyn std::error::Error>> {
    let cfg = load_config(config_path)?;
    println!("app.toml validation succeeded for {}", cfg.app.name);
    Ok(())
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let cli = Cli::parse();
    match cli.command {
        Commands::GenerateIcons => run_generate_icons(),
        Commands::Check { config } => run_check(&config),
        Commands::Codegen { config, check } => run_codegen(&config, check),
        Commands::NewApp {
            config,
            out,
            with_sample,
            dry_run,
        } => run_new_app(&config, &out, with_sample, dry_run),
        Commands::Guard { only } => guard::run_guard(only.as_deref()),
        Commands::GccMock { port } => {
            let rt = tokio::runtime::Runtime::new()?;
            rt.block_on(gcc_mock::run_mock_server(port))
        }
    }
}
