use convert_case::{Case, Casing};
use std::fs;
use std::path::Path;

pub fn generate_bindings(repo_root: &Path) -> Result<(), Box<dyn std::error::Error>> {
    let commands_path = repo_root.join("crates/caf-app/src/commands.rs");
    if !commands_path.exists() {
        return Err(format!("commands.rs not found at {:?}", commands_path).into());
    }

    let code = fs::read_to_string(&commands_path)?;
    let syntax_tree = syn::parse_file(&code)?;

    let mut generated_ts = String::from(
        "// THIS FILE IS AUTOMATICALLY GENERATED BY `cargo xtask codegen`. DO NOT EDIT MANUALLY.\n\
        import { invoke } from '@tauri-apps/api/core';\n\n",
    );

    let mut has_commands = false;

    for item in syntax_tree.items {
        if let syn::Item::Fn(func) = item
            && has_tauri_command_attr(&func.attrs)
        {
            let name = func.sig.ident.to_string();

            let mut ts_args = Vec::new();
            let mut invoke_args = Vec::new();

            for input in func.sig.inputs {
                if let syn::FnArg::Typed(pat_type) = input
                    && let syn::Pat::Ident(pat_ident) = *pat_type.pat
                {
                    let arg_name_snake = pat_ident.ident.to_string();
                    let arg_name_camel = arg_name_snake.to_case(Case::Camel);

                    // Naive type translation for basic params (most complex types go through ts-rs)
                    let ts_type = rust_type_to_ts(&pat_type.ty);

                    ts_args.push(format!("{}: {}", arg_name_camel, ts_type));
                    invoke_args.push(format!("{}: {}", arg_name_snake, arg_name_camel)); // tauri expects snake_case if backend defined it that way
                }
            }

            let ret_type = rust_ret_to_ts(&func.sig.output);

            let ts_args_str = ts_args.join(", ");
            let invoke_args_str = if invoke_args.is_empty() {
                "".to_string()
            } else {
                format!(", {{ {} }}", invoke_args.join(", "))
            };

            generated_ts.push_str(&format!(
                "export async function invoke_{}({}): Promise<{}> {{\n  return invoke('{}'{});\n}}\n\n",
                name.to_case(Case::Camel),
                ts_args_str,
                ret_type,
                name,
                invoke_args_str
            ));

            has_commands = true;
        }
    }

    if has_commands {
        let out_path = repo_root.join("frontend/src/lib/api/generated_bindings.ts");
        if let Some(parent) = out_path.parent() {
            fs::create_dir_all(parent)?;
        }
        fs::write(out_path, generated_ts)?;
        println!("TypeScript bindings successfully generated.");
    }

    Ok(())
}

fn has_tauri_command_attr(attrs: &[syn::Attribute]) -> bool {
    attrs.iter().any(|attr| {
        let path_segments: Vec<String> = attr
            .path()
            .segments
            .iter()
            .map(|s| s.ident.to_string())
            .collect();
        path_segments == vec!["tauri", "command"]
    })
}

fn rust_type_to_ts(ty: &syn::Type) -> String {
    match ty {
        syn::Type::Path(type_path) => {
            let seg = type_path.path.segments.last().unwrap();
            let ident = seg.ident.to_string();
            match ident.as_str() {
                "String" | "str" => "string".to_string(),
                "u8" | "u16" | "u32" | "u64" | "i8" | "i16" | "i32" | "i64" | "f32" | "f64"
                | "usize" | "isize" => "number".to_string(),
                "bool" => "boolean".to_string(),
                "serde_json::Value" | "Value" => "any".to_string(),
                "Vec" => {
                    if let syn::PathArguments::AngleBracketed(args) = &seg.arguments
                        && let Some(syn::GenericArgument::Type(inner)) = args.args.first()
                    {
                        format!("{}[]", rust_type_to_ts(inner))
                    } else {
                        "any[]".to_string()
                    }
                }
                "Option" => {
                    if let syn::PathArguments::AngleBracketed(args) = &seg.arguments
                        && let Some(syn::GenericArgument::Type(inner)) = args.args.first()
                    {
                        format!("{} | null", rust_type_to_ts(inner))
                    } else {
                        "any | null".to_string()
                    }
                }
                "Window" | "AppHandle" => "any".to_string(),
                _ => "any".to_string(),
            }
        }
        syn::Type::Reference(type_ref) => rust_type_to_ts(&type_ref.elem),
        _ => "any".to_string(),
    }
}

fn rust_ret_to_ts(output: &syn::ReturnType) -> String {
    match output {
        syn::ReturnType::Default => "void".to_string(),
        syn::ReturnType::Type(_, ty) => {
            // Simplify Result<T, E> to T
            if let syn::Type::Path(type_path) = &**ty {
                let seg = type_path.path.segments.last().unwrap();
                if seg.ident == "Result"
                    && let syn::PathArguments::AngleBracketed(args) = &seg.arguments
                    && let Some(syn::GenericArgument::Type(inner_ty)) = args.args.first()
                {
                    return rust_type_to_ts(inner_ty);
                }
            }
            rust_type_to_ts(ty)
        }
    }
}
