// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AiChatResponse = { message: string, redactions_applied: number, tokens_used: number | null, };
