// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiMode } from "./AiMode";
import type { PrivacyLevel } from "./PrivacyLevel";

export type AiSettings = { mode: AiMode, base_url: string, model: string, temperature: number, response_language: string, tone: string, custom_instructions: string, privacy_level_default: PrivacyLevel, allow_full_detail_for_local: boolean, has_api_key: boolean, };
