// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrivacyLevel } from "./PrivacyLevel";

export type ContextPayload = { level: PrivacyLevel, content: string, redacted_count: number, };
